// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419172135_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Regla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MontoMinimo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Regla", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MontoMinimo = 0.00m,
                            Porcentaje = 0.06m
                        },
                        new
                        {
                            Id = 2,
                            MontoMinimo = 500.00m,
                            Porcentaje = 0.08m
                        },
                        new
                        {
                            Id = 3,
                            MontoMinimo = 800.00m,
                            Porcentaje = 0.10m
                        },
                        new
                        {
                            Id = 4,
                            MontoMinimo = 1000.00m,
                            Porcentaje = 0.15m
                        });
                });

            modelBuilder.Entity("Backend.Models.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vendedor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Juan Pérez"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "María García"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Carlos López"
                        });
                });

            modelBuilder.Entity("Backend.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<int>("VendedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VendedorId");

                    b.ToTable("Venta", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaVenta = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 500.00m,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 2,
                            FechaVenta = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 600.00m,
                            VendedorId = 1
                        },
                        new
                        {
                            Id = 3,
                            FechaVenta = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 600.00m,
                            VendedorId = 2
                        },
                        new
                        {
                            Id = 4,
                            FechaVenta = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 200.00m,
                            VendedorId = 3
                        },
                        new
                        {
                            Id = 5,
                            FechaVenta = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 100.00m,
                            VendedorId = 3
                        });
                });

            modelBuilder.Entity("Backend.Models.Venta", b =>
                {
                    b.HasOne("Backend.Models.Vendedor", "Vendedor")
                        .WithMany("Ventas")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Backend.Models.Vendedor", b =>
                {
                    b.Navigation("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
